### PR TITLE
Prevent parse-gerber to parse object attributes

### PR DESCRIPTION
**Pull request by netquik**
Prevent Object Attributes (TO) attributes from being parsed as operations or commands
Fixes https://github.com/tracespace/tracespace/issues/375

### CODE REVIEW

**Comment by netquik** [comment]
I tested locally my git clone "patch-1" 
https://github.com/netquik/tracespace/tree/patch-1

and fixes https://github.com/tracespace/tracespace/issues/375

**Comment by mcous** [comment]
I went to release this as `v4.2.6`, only to find that TravisCI for open-source isn't really a thing anymore... I will see what I can do about back-porting the GitHub Actions setup from the `v5` branch; please stand by.

**Comment by kasbah** [comment]
I was able to automatically migrate the Kitspace TravisCI to travis-ci.com a while back. Eventually I ran out of minutes (and did migrate to GH Actions) but that may not be a problem here if these job don't run that often.

**Comment by mcous** [comment]
_Finally_ released as `v4.2.7` 🚢

**Pull request merged**
