### PR TITLE
Remove .null . null from out file name

### PR DESCRIPTION
**Pull request by darkworks**
Remove .null . null from out file name

previously output was filename.extension.null.null.svg now .null will be removed and out put will be filename.extension.svg

### CODE REVIEW

**Comment by darkworks** [comment]
ok i removed the semi color not sure why check failed , i think its good to put semi colon it end of line , maybe node js have different rules of set as am not node js developer , i work with js on front end little bit and use semi colon it end of lines everytime. 
+ i tried to set null check and set file name it line #118 but that not work getting error layer is not defined.  not sure maybe the syntax is bit new to me because am classic code

i tried to do something like 

```
  function writeRenders(stackup) {
    const name = inferBoardName(stackup)
    const ensureDir =
      argv.out !== options.out.STDOUT ? makeDir(argv.out) : Promise.resolve()

		let fileName = layer.filename
		if(layer.side != null)
			fileName += '.'+layer.side
		if(layer.type != null)
		  fileName += '.'+layer.side	

		 fileName += '.svg' // add extension to file name
    return ensureDir.then(() =>
      Promise.all([
        !argv.noBoard && writeOutput(`${name}.top.svg`, stackup.top.svg),
        !argv.noBoard && writeOutput(`${name}.bottom.svg`, stackup.bottom.svg),
        ...stackup.layers
          .filter(_ => !argv.noLayer)
          .map(layer =>
            writeOutput(
              fileName,
              gerberToSvg.render(layer.converter, layer.options.attributes)
            )
          ),
      ])
    )
  }
```

**Comment by mcous** [comment]
@darkworks you're getting close, but the reason your snippet above doesn't work is because `layer` isn't in scope until inside of the `map` iterator on line 116.

```js
  function writeRenders(stackup) {
    const name = inferBoardName(stackup)
    const ensureDir =
      argv.out !== options.out.STDOUT ? makeDir(argv.out) : Promise.resolve()

    return ensureDir.then(() =>
      Promise.all([
        !argv.noBoard && writeOutput(`${name}.top.svg`, stackup.top.svg),
        !argv.noBoard && writeOutput(`${name}.bottom.svg`, stackup.bottom.svg),
        ...stackup.layers
          .filter(_ => !argv.noLayer)
          .map(layer => {
            let filename = layer.filename
            if (layer.side) filename += `.${layer.side}`
            if (layer.type) filename += `.${layer.type}`

            return writeOutput(
              `${filename}.svg`,
              gerberToSvg.render(layer.converter, layer.options.attributes)
            )
          }),
      ])
    )
  }
```

**Please `npm run format` and `npm run lint` before commiting**. Your code is still failing stylechecking and the `format` and `lint` scripts will catch those errors before you submit

---
P.S. regarding semicolons: most of the time semicolons are optional in JavaScript (Node, browser, whatever). The ["standard" JS linter](https://standardjs.com/rules.html#semicolons) has a good description about semicolon usage.

I switched my projects to no-semicolons because I work in other languages that don't use semicolons, and I didn't like having to switch my brain back and forth. You should use whatever makes you happy in your own projects, though!

**Comment by darkworks** [comment]
sorry i was busy in some work 

i tried to run npm format command from cli but its not not working saying scripts missing 
i tried like npm run format cli.js    and  npm run cli.js format   

i formated the cli.js file in visual studio code not sure will be enough or not

**Comment by mcous** [comment]
@darkworks please see the [contributing section](https://github.com/tracespace/tracespace#contributing) of the readme for development setup instructions. All development scripts should be run from the top-level of the repository:

```shell
cd tracespace
npm run format
```

Are you planning on making my requested changes to this PR? If yes, I'm happy to leave the PR open until you have time to work on it

**Comment by darkworks** [comment]
thanks for the help 
so i did : `git clone git@github.com:tracespace/tracespace.git`
that not worked for me 
i changed it to 
`git clone https://github.com/tracespace/tracespace`

which clone the lib   ( regarding i have sent pull request for correction )

after that i did 

```
cd tracespace
npm run format
```

which was give me error prettier is not recognized internal command. 
so for fix i did
`npm install prettier`

after that `npm run format`  start giving me error
`'yml)'' is not recognized as an internal or external command,`

i  run `npm install yml`  but it not fixed the issue , am not sure why its displaying `yml)`   special characters should not be in npm command

sorry this pull request had create trouble for you , issues arising in it ,

**Comment by mcous** [comment]
@darkworks thanks for the PR, I'm about to merge it. Regarding your other comments:

> i did: git clone git@github.com:tracespace/tracespace.git... that not worked for me

You must have your [SSH client properly configured](https://help.github.com/en/articles/connecting-to-github-with-ssh) to clone repositories via SSH

> which was give me error prettier is not recognized internal command

Please read through the contributing section of this project's README and look into general instructions for developing npm packages. With almost all Node/JavaScript projects (this one included), the first step after cloning is to install package dependencies (like prettier) by running `npm install` by itself:

```shell
git clone git@github.com:tracespace/tracespace.git
cd tracespace
npm install
```

> after that npm run format start giving me error
> 'yml)'' is not recognized as an internal or external command,

That's odd and unexpected. What operating system are you on?

**Comment by mcous** [comment]
This has been released as `@tracespace/cli@4.1.1`. Thanks for your help @darkworks!

**Comment by darkworks** [comment]
> @darkworks thanks for the PR, I'm about to merge it. Regarding your other comments:
> 
> > i did: git clone [git@github.com](mailto:git@github.com):tracespace/tracespace.git... that not worked for me
> 
> You must have your [SSH client properly configured](https://help.github.com/en/articles/connecting-to-github-with-ssh) to clone repositories via SSH
> 
> > which was give me error prettier is not recognized internal command
> 
> Please read through the contributing section of this project's README and look into general instructions for developing npm packages. With almost all Node/JavaScript projects (this one included), the first step after cloning is to install package dependencies (like prettier) by running `npm install` by itself:
> 
> ```shell
> git clone git@github.com:tracespace/tracespace.git
> cd tracespace
> npm install
> ```
> 
> > after that npm run format start giving me error
> > 'yml)'' is not recognized as an internal or external command,
> 
> That's odd and unexpected. What operating system are you on?

am using windows 7 operating system

**Pull request merged**
